### ISSUE TITLE
Python 3.7 / Linux Wheel

### ISSUE THREAD

**Issue by kloppjp** [tensorflow/compression#35]
Unfortunately, PyPi only has wheels up to python 3.6 for linux available (https://pypi.org/project/tensorflow-compression/#files). If you could add 3.7, that would make things even a little smoother.

Anyway, thanks a lot for you work on the library!

**Comment by jonycgn** [comment]
Hi Jan,

thanks for your feedback. We don't currently have 3.7/Linux binaries because the build environment hadn't been provided by the TensorFlow team at the time we wrote our build system (and building Linux binaries that work across different versions of dependencies is hard). I believe they've made some updates in the last couple of months. If possible, we'll incorporate your suggestion for the next release.

Leaving this bug open as a reminder.

**Comment by jonycgn** [comment]
The beta release now has support for Python 3.5 to 3.8 (same as TensorFlow).
