### ISSUE TITLE
Getting stuck in one point during training

### ISSUE THREAD

**Issue by s172444s** [tensorflow/compression#61]
Hello,
I use python 3.6 installed on miniconda in a Linux OS. I have installed tensorflow 1.15 and tensorflow compression 1.3 on the machine. I ran the command "python -m hific.train --config mselpips --ckpt_dir ckpts/mse_lpips --num_steps 1M --tfds_dataset_name coco2014" and the code starts training but after the step "Downloading LPIPS weights: http://rail.eecs.berkeley.edu/models/lpips/net-lin_alex_v0.1.pb -> lpips_weight__net-lin_alex_v0.1.pb", it gets idle and does not do anything.

In advance, I appreciate your time and answers.

**Comment by fab-jul** [comment]
Hey, this may be due to stdout not getting shown? We will shortly release the final version of the HiFiC code, you can check it out already at my fork: [fab-jul/compression](https://github.com/fab-jul/compression). One of the diffs is a fix to the logging flags of TensorFlow. Let me know if this helps!

**Comment by fab-jul** [comment]
It seems this update landed today! So please check if L27 in train.py starts with `tf.logging` as [in the current master](https://github.com/tensorflow/compression/blob/master/models/hific/train.py#L27).

**Comment by s172444s** [comment]
Dear Fabian,

Thank you very much for your quick response.

Sincerely,
Vahid.

**Comment by jonycgn** [comment]
Hi, I'm assuming this issue is resolved. In case it isn't, please reopen.
